# Site Settings
title: ResiHub
#baseurl: "/lab-community" # Leave empty if your site is at the root domain
#url: "https://lab-community.pages.dev"

# Settings to fix the subfolder paths
baseurl: ""
url: "https://dekumar2-lab.github.io"

# Ensure Jekyll looks into these folders for your guides
include: [content, assets]

# Optional: Set a default theme as a fallback
theme: jekyll-theme-cayman
