# Site Settings
title: ResiHub
baseurl: ""
url: "https://dekumar2-lab.github.io"

# 1. Define the Marketplace Collection
collections:
  pros:
    output: true
    permalink: /marketplace/:name/

# 2. Ensure Jekyll includes your content
include: [content, assets, _pros]

theme: jekyll-theme-cayman
